# Conexión a la base de datos local
spring.datasource.url=jdbc:postgresql://localhost:5432/portafolio_db
spring.datasource.username=postgres
spring.datasource.password=root

# Magia de Spring: Crea y actualiza las tablas automáticamente basándose en su código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ==========================================
# CONFIGURACIÓN DE CORREO (JavaMailSender)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Ponga aquí el correo desde donde se enviarán los mensajes
spring.mail.username=jorgeglicona@gmail.com
# Pegue aquí su contraseña de aplicación de 16 letras (sin espacios)
spring.mail.password=oihs bldh qkzc crkm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true